version: '3.8'
services:
  catalogservice:
    build:
      context: .
      dockerfile: CatalogService.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CatalogDb=Host=postgres;Database=CatalogDb;Username=postgres;Password=yourpassword

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: netshop_user
      POSTGRES_PASSWORD: N3tSh0p#2025
      POSTGRES_DB: CatalogDb
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
